### ISSUE TITLE
Unstable features prevent building on Rust beta

### ISSUE THREAD

**Issue by Ape** [SiegeLord/RustAllegro#3]
RustAllegro cannot be build on Rust beta since it uses a unstable features ```libc```, ```std_misc```, and ```optin_builtin_traits```.

* ```libc``` should be replaced with [libc crate](https://github.com/rust-lang/libc).
* ```optin_builtin_traits``` should be replaced with marker types.
* I am not sure how to replace ```std_misc```.

**Comment by Ape** [comment]
I fixed ```libc``` with commit b326a23332288504b26fbbbdf3d466a09c85b809, but the other issues remain open.

**Comment by SiegeLord** [comment]
I'm aware of this issue, but it is low priority since one can just use the nightly compiler. I'll get around it someday.

**Comment by SiegeLord** [comment]
Ok, so I eliminated many of the unstable features from the crates, but some have to remain. `std_misc` must be there, as otherwise this binding will not safely work on OSX. I've also added the `exit_status` feature as otherwise the panics inside Rust code will not result in a failed exit status ofthe program.

In return, you can now write programs that use this crate without any stable features (as I've removed the requirement for the `start` feature).

**Comment by SiegeLord** [comment]
Rust 1.1 fixed the `exit_status` issue, and I worked around the `std_misc` issue, so as of 0.0.18 RustAllegro should build on Rust stable.
